default_language_version:
  python: python3
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        language: python
        args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language: python
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: dicomtrolley/xml_templates.py
        language: python
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-docstrings
          - mccabe
          - yesqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-requests
          - types-Jinja2