default_language_version:
  python: python3
exclude: pimsclient/autogen  # avoid terrible black+mypy fights
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        language: python
        args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language: python
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language: python
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-docstrings
          - mccabe
          - yesqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
      - id: mypy
        exclude: "pimsclient/swagger_models_v0.*"
        additional_dependencies:
          - "pydantic>=1.10.4"
          - types-requests
          - types-Jinja2